### ISSUE TITLE
Question! How can i send data to Atlas?

### ISSUE THREAD

**Issue by kennedyoliveira** [Netflix/spectator#268] opened 2016-02-19 12:49 UTC
Hello everyone!

I'm trying to use spectator + atlas but i didn't see anywhere how can i send that data to atlas?

Could someone point a reference, documentation, example or something?

Thank you.

**Comment by brharrington** [comment] 2016-02-19 13:02
Right now we do it via the servo registry, for more details see https://github.com/Netflix/spectator/issues/239#issuecomment-154186397. I'll look at updating the wiki with a more specific reference for that. I'm going to close this as a duplicate of the other issue.

**Closed by brharrington** 2016-02-19 13:02 UTC
Labels: question
